app/models/apiary.py
from ..extensions import db

class Apiary(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))
    beeCount = db.Column(db.Integer)
    breed = db.Column(db.String(20))
    hiveType = db.Column(db.String(20))
    feed = db.Column(db.String(10))
    
    latitude = db.Column(db.Float, nullable=False)
    longitude = db.Column(db.Float, nullable=False)
    

app/models/user.py
from .apiary import Apiary
from ..extensions import db, login_manager
from datetime import datetime
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    apiaries = db.relationship(Apiary, backref='owner')
    status = db.Column(db.String(50), default='user')
    avatar = db.Column(db.String(200))
    name = db.Column(db.String(50))
    login = db.Column(db.String(50))
    password = db.Column(db.String(200))
    date = db.Column(db.DateTime, default = datetime.utcnow)

app/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import BooleanField, FileField, PasswordField, StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Length, Email, EqualTo

from .models.user import User

class RegistrationForm(FlaskForm):
    name = StringField('ФИО', validators=[DataRequired(), Length(min=2, max=100)])
    login = StringField('Логин', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Пароль', validators=[DataRequired()])
    confirm_password = PasswordField('Подтвердите пароль', validators=[DataRequired(), EqualTo('password')])
    avatar = FileField('Загрузите фото', validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    submit = SubmitField('Зарегестрироваться')
    
    def validate_login(self, login):
        user = User.query.filter_by(login=login.data).first()
        if user:
            raise ValidationError("Данное имя пользователя уже занято. Пожалуйста, выберите другое..")
        
class LoginForm(FlaskForm):
    login = StringField('Логин', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember = BooleanField("Запомнить меня")
    submit = SubmitField('Войти')

app/__init__.py
from flask import Flask
from .extensions import db, migrate, login_manager, assets
from .bundles import bundles, register_bundles
from .config import Config

from .routes.user import user
from .routes.apiary import apiary
from .routes.main import main

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    
    app.register_blueprint(main)
    app.register_blueprint(user)
    app.register_blueprint(apiary)
    
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    assets.init_app(app)
    
    # LOGIN MANAGER
    login_manager.login_view = 'user.login'
    login_manager.login_message = 'Для доступа к данной странице необходима авторизация'
    login_manager.login_message_category = "info"
    
    # ASSETS
    register_bundles(assets, bundles)
    
    with app.app_context():
        db.create_all()
        
    return app

app/routes/apiary.py
from flask import Blueprint, abort, flash, render_template, request, redirect
from flask_login import current_user, login_required
from ..extensions import db
from ..models.apiary import Apiary
from geopy.distance import geodesic

apiary = Blueprint('apiary', __name__)

@apiary.route('/apiary/all', methods=['POST', 'GET'])
def all():
    notes = Apiary.query.all()
    return render_template('apiary/all.html', notes=notes)

@apiary.route('/apiary/create', methods=['POST', 'GET'])
@login_required
def create():
    if request.method == 'POST':
        beeCount= request.form.get('beeCount')
        breed = request.form.get('breed')
        hiveType = request.form.get('hiveType')
        feed = request.form.get('feed')
        latitude = request.form.get('latitude')
        longitude = request.form.get('longitude')

        all_apiaries = Apiary.query.all()
        for apiary in all_apiaries:
            distance = geodesic((latitude, longitude), (apiary.latitude, apiary.longitude)).meters
            if distance < 1000:  # Пороговое расстояние в метрах
                flash("Пасеки расположены слишком близко!", "danger")
        apiary = Apiary(name=current_user.id, beeCount=beeCount, breed=breed, hiveType=hiveType, feed=feed, latitude=latitude, longitude=longitude)
        
        try:
            db.session.add(apiary)
            db.session.commit()
            flash("Пасека успешно добавлена!", "success")
            return redirect('/')
        except Exception as e:
            print(str(e))
    else:
        return render_template('apiary/create.html')
    
@apiary.route('/apiary/<int:id>/update', methods=['POST', 'GET'])
@login_required
def update(id):
    apiary = Apiary.query.get(id)
    
    if apiary.owner.id == current_user.id:
        if request.method == 'POST':
            apiary.beeCount= request.form.get('beeCount')
            apiary.breed = request.form.get('breed')
            apiary.hiveType = request.form.get('hiveType')
            apiary.feed = request.form.get('feed')        
            try:
                db.session.commit()
                return redirect('/')
            except Exception as e:
                print(str(e))
        else:
            return render_template('apiary/update.html', apiary = apiary)
    else:
        abort(403)
    
@apiary.route('/apiary/<int:id>/delete', methods=['POST', 'GET'])
def delete(id):
    apiary = Apiary.query.get(id)
    try:
        db.session.delete(apiary)
        db.session.commit()
        flash("Пасека успешно удалена!", "success")
        return redirect('/')
    except Exception as e:
        print(str(e))
    

app/routes/main.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)

@main.route('/index')
@main.route('/')
def index():
    return render_template('main/index.html')

@main.route('/rules')
def rules():
    return render_template('main/rules.html')

app/routes/user.py
from flask import Blueprint, redirect, render_template, flash, url_for, request
from flask_login import login_user, logout_user

from ..functions import save_picture
from ..forms import RegistrationForm, LoginForm
from ..extensions import db, bcrypt
from ..models.user import User

user = Blueprint('user', __name__)

@user.route('/user/register', methods=['POST', 'GET'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        avatar_filename = save_picture(form.avatar.data)
        user = User(name=form.name.data, login = form.login.data, avatar = avatar_filename, password = hashed_password)
        try:
            db.session.add(user)
            db.session.commit()
            flash(f"Вы успешно зарегестрированы", "success")
            return redirect(url_for('user.login'))
        except Exception as e:
            print(str(e))
            flash(f"Ошибка регистрации", "danger")
    return render_template('user/register.html', form=form)

@user.route('/user/login', methods=['POST', 'GET'])
def login():
    form = LoginForm() 
    if form.validate_on_submit():
        user = User.query.filter_by(login=form.login.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash("Вы успешно авторизованы!", "success")
            return redirect(next_page) if next_page else redirect(url_for('main.index'))     
        else:
            flash("Ошибка входа. Проверьте логин и пароль!", "danger")
    return render_template('user/login.html', form=form)

@user.route('/user/logout', methods=['POST', 'GET'])
def logout():
    logout_user()
    return redirect(url_for('main.index'))  

app/templates/apiary/all.html
{% extends 'main/base.html' %}

{%block title%} Пасеки на нашем сайте {%endblock%}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/table.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/libs/font-awesome.min.css') }}">
{% endblock %}

{%block content%}
<div class="container">
	<table cellpadding="0" cellspacing="0" border="0">
		<thead>
			<tr>
				<th>Фото</th>
				<th>ФИО владельца</th>
				<th>Количество пчёл</th>
				<th>Порода</th>
				<th>Тип улея</th>
				<th>Питание для пчёл</th>
				<th>Расположение</th>
				<th>Действие</th>
			</tr>
		</thead>
		<tbody>
            {% for notes in notes  %}
			<tr>
				<td>
					<img width="96px" height="96px" src="{{ url_for('static', filename='upload/'+notes.owner.avatar) }}" alt="Владелец">
				</td>
				<td>
					{{notes.owner.name}}
				</td>
				<td>{{notes.beeCount}}</td>
				<td>{{notes.breed}}</td>
				<td>{{notes.hiveType}}</td>
				<td>{{notes.feed}}</td>
				<td>
					{{notes.latitude}}
					{{notes.longitude}}
				</td>

				<td>
					{% if current_user.is_authenticated and notes.owner.id == current_user.id %}
						<a href="{{ url_for('apiary.update', id=notes.id) }}" class="btn btn-sm btn-secondary"><span class="fa fa-edit"></span></a>
						<a href="{{ url_for('apiary.delete', id=notes.id) }}"class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
					{% endif %}
				</td>
            </tr>
            {% endfor %}
		</tbody>
	</table>
</div>
{%endblock%} 

app/templates/apiary/create.html
 {% extends 'main/base.html' %}

 {%block title%} Добавление пасеки {%endblock%}

 {%block content%}
 <form method="post" class="form-control d-flex flex-column gap-2">
    <input name="beeCount" type="text" placeholder="Количество пчёл" class="form-control">
    <input name="breed" type="text" placeholder="Порода" class="form-control">
    <input name="hiveType" type="text" placeholder="Тип улея" class="form-control">
    <input name="feed" type="text" placeholder="Питание для пчёл" class="form-control">

    <!-- Поля для хранения координат -->
    <input type="hidden" name="latitude" id="latitude">
    <input type="hidden" name="longitude" id="longitude">
    
    <!-- Карта для выбора местоположения -->
    <div id="map" style="height: 400px; margin-bottom: 10px;"></div>

    <input value="Добавить" type="submit" class="btn btn-success">
 </form>

 <!-- Подключение Leaflet -->
 <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
 <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

 <script>
   // Инициализация карты
   var map = L.map('map').setView([56.3287, 44.002], 10); // Центр карты — Нижний Новгород

   // Добавление слоя карты
   L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
       maxZoom: 19,
   }).addTo(map);

   var marker;

   // Обработчик клика на карте для установки маркера и получения координат
   map.on('click', function(e) {
       if (marker) {
           map.removeLayer(marker);
       }
       marker = L.marker(e.latlng).addTo(map);
       
       // Установка значений широты и долготы в скрытые поля формы
       document.getElementById('latitude').value = e.latlng.lat;
       document.getElementById('longitude').value = e.latlng.lng;
   });
</script>
{%endblock%}

app/templates/apiary/update.html
{% extends 'main/base.html' %}

{%block title%} Редактирование пасеки {%endblock%}

{%block content%}
<form method="post" class="form-control d-flex flex-column gap-2">
   <input value='{{ apiary.beeCount }}'' name="beeCount" type="text" placeholder="Количество пчёл" class="form-control">
   <input value='{{ apiary.breed }}' name="breed" type="text" placeholder="Порода" class="form-control">
   <input value='{{ apiary.hiveType }}' name="hiveType" type="text" placeholder="Тип улея" class="form-control">
   <input value='{{ apiary.feed }}' name="feed" type="text" placeholder="Питание для пчёл" class="form-control">
   <input value="Обновить" type="submit" class="btn btn-success">
</form>
{%endblock%}

app/templates/main/_flash.html
{% block styles_scripts %}
<style>
    .error { color: red; text-align: center; }
    .success { color: green; text-align: center; }
</style>
{% endblock %}

{% for category, message in get_flashed_messages(with_categories=true) %}
    <div class="alert alert-{{ category }}">
      {{message}}
    </div>
{% endfor %}

app/templates/main/_footer.html
<ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="{{ url_for('main.index') }}" class="nav-link px-2 text-body-secondary">Главая страница</a></li>
    {% if current_user.is_authenticated %}
        <li class="nav-item"><a href="{{ url_for('apiary.create') }}" class="nav-link px-2 text-body-secondary">Добавить пасеку</a></li>
    {% endif %}
    <li class="nav-item"><a href="{{ url_for('apiary.all') }}" class="nav-link px-2 text-body-secondary">Наши пасеки</a></li>
    <li class="nav-item"><a href="{{ url_for('main.rules') }}" class="nav-link px-2 text-body-secondary">Правила</a></li>
</ul>

app/templates/main/_header.html
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <div class="col-md-3 mb-2 mb-md-0">
      <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
        <img class="header__img" src="{{ url_for('static', filename='img/logo.png') }}" alt="bee">
      </a>
    </div>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><a href="/" class="nav-link px-2 link-secondary">Главная страница</a></li>
      {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('apiary.create') }}" class="nav-link px-2">Добавить пасеку</a></li>
      {% endif %}
      
      <li><a href="{{ url_for('apiary.all') }}" class="nav-link px-2">Наши пасеки</a></li>
      <li><a href="{{ url_for('main.rules') }}" class="nav-link px-2">Правила</a></li>
    </ul>

    <div class="col-md-3 text-end">
      {% if current_user.is_authenticated %}
          <a href="{{ url_for('user.logout') }}" class="btn btn-outline-primary me-2">Выйти</a>
      {% else%}
          <a href="{{ url_for('user.login') }}" class="btn btn-outline-primary me-2">Войти</a>
          <a href="{{ url_for('user.register') }}" class="btn btn-primary">Регистрация</a>
      {% endif %}
    </div>
  </header>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{url_for('static', filename = 'css/libs/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename = 'css/libs/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename = 'css/main.css')}}">

    <!-- Подключение Leaflet -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block style %}{% endblock %}
    <title> {% block title %}{% endblock %}</title>
</head>

<body>
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <header class="header">{% include 'main/_header.html' %}</header>
    {% include 'main/_flash.html' %}
    
    <div class="page">
        <main class="content">
            <h1>{{ self.title() }}</h1>
            {% block content %}{% endblock %}
        </main>
        <footer class="py-3 my-4">{% include 'main/_footer.html' %}</footer>
    </div>

    <script src="{{ url_for('static', filename='js/libs/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>

</html>

app/templates/main/index.html
{% extends 'main/base.html' %}

{%block title%} Главная страница {%endblock%}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/info.css') }}">
{% endblock %}

{%block content%}
<main>
        <h2>
            Добро пожаловать на сайт пчеловодов Нижегородской области!
        </h2>
        <p>
            Наш сайт создан для объединения и поддержки всех, кто занимается пчеловодством в нашем регионе. Независимо от того, являетесь ли вы опытным пчеловодом или только начинаете свой путь в этом удивительном деле, здесь вы найдете много полезной информации, советов и ресурсов.
        </p>
        <h2>
            Пчеловодство в Нижегородской области
        </h2>

        <p>
            Количество пчелиных семей в области недостаточно для надежного опыления сельхозкультур, особенно рапса. Большое разнообразие дикорастущих медоносов создают благоприятные условия для увеличения количества пчелиных семей в области.
        </p>    

        <p>
            Перспективными направлениями в развитии пчеловодства является  получение продуктов пчеловодства – обножка, перга, прополис, воск и т.д. Развитие этого направления требует стабильного рынка сбыта продукции. 
        </p>
        <p>
            Для пасек в экологически чистых территориях перспективным может стать фармакологическое направление развития пчеловодства, а вблизи санаториев и домов отдыха и медицинское его направление (с отпуском процедур пчелоужаления и использования на месте скоропортящихся нативных продуктов пчеловодства).
        </p>

{%endblock%}

app/templates/main/rules.html
{% extends 'main/base.html' %}

{%block title%} Правила сайта {%endblock%}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/info.css') }}">
{% endblock %}

{%block content%}
    <h2>Правила использования сайта для пчеловодов Нижегородской области</h2>
    <p><b>1. Общие положения</b> <br>1.1. Сайт предназначен для обмена информацией, новостями и ресурсами, связанными с пчеловодством в Нижегородской области. <br>1.2. Использование сайта подразумевает согласие с данными правилами. Пожалуйста, внимательно ознакомьтесь с ними.</p>
    <p><b>2. Регистрация и учетные записи</b><br>2.1. Для доступа к определенным функциям сайта может потребоваться регистрация и создание учетной записи. <br>2.2. Пользователи обязуются предоставлять точную и актуальную информацию при регистрации. 2.3. Пользователь несет ответственность за сохранность своих учетных данных и за все действия, произведенные с их учетной записью.</p>
    <p><b>3. Конфиденциальность и безопасность</b><br>3.1. Сайт принимает меры для обеспечения безопасности и конфиденциальности личных данных пользователей. <br>3.2. Пользователи обязуются не раскрывать свои учетные данные третьим лицам и уведомлять администрацию о любых подозрительных действиях, связанных с их учетной записью.</p>
    <p><b>4. Ответственность</b><br>4.1. Администрация сайта не несет ответственности за содержание пользовательских публикаций и за возможный ущерб, причиненный ими. <br>4.2. Пользователи несут полную ответственность за свои действия на сайте и за соблюдение всех применимых законов и правил.</p>
    <p><b>5. Изменение правил</b> <br>5.1. Администрация сайта имеет право изменять данные правила в любое время. <br>5.2. Изменения будут опубликованы на сайте, и пользователи обязаны регулярно проверять актуальность правил.</p>
{%endblock%}

app/templates/user/login.html
{% extends 'main/base.html' %}

{%block title%} Авторизация {%endblock%}

{%block content%} 
    <form method="post", class="form-control d-flex flex-column gap-2">
        {{  form.csrf_token }}
        {{  form.login(class='form-control', placeholder = 'Логин') }}
        {{  form.password(class='form-control', placeholder = 'Пароль') }}
        <div class="d-flex flex-row justify-content-center gap-2">
            {{  form.remember.label }} {{ form.remember(class="form-check") }}
        </div>
        {{  form.submit(class="btn btn-success") }}
    </form>
{%endblock%}

app/templates/user/register.html
{% extends 'main/base.html' %}

{%block title%} Регистрация {%endblock%}

{%block content%} 
    <form method="post" enctype="multipart/form-data", class="form-control d-flex flex-column gap-2">
        {{  form.csrf_token }}
        {{  form.name(class='form-control', placeholder = 'ФИО') }}
        {{  form.login(class='form-control', placeholder = 'Логин') }}

        {%if form.login.errors%}
            <div class="invalid-feedback" style="display: block!important;">
                {% for error in form.login.errors %}
                    <span> {{error}} </span>
                {% endfor %}
            </div>
        {%endif%}

        {{  form.avatar(class='form-control') }}
        {{  form.password(class='form-control', placeholder = 'Пароль') }}
        {{  form.confirm_password(class='form-control', placeholder = 'Повторите пароль') }}
        {{  form.submit(class="btn btn-success") }}
    </form>
{%endblock%}